import { useData } from "../hooks/useData";
import Card from "../components/Card";
import Loader from "../components/Loader";
import styles from "./Overview.module.css";

function StatBox({ label, value, sub, color }) {
  return (
    <div className={styles.stat}>
      <div className={styles.statValue} style={{ color: color ?? "var(--accent)" }}>
        {value}
      </div>
      <div className={styles.statLabel}>{label}</div>
      {sub && <div className={styles.statSub}>{sub}</div>}
    </div>
  );
}

export default function Overview() {
  const { data: demo,  loading: l1, error: e1 } = useData("/data/demographics.json");
  const { data: conds, loading: l2, error: e2 } = useData("/data/top_conditions.json");
  const { data: enc,   loading: l3, error: e3 } = useData("/data/encounter_classes.json");
  const { data: out,   loading: l4, error: e4 } = useData("/data/covid_outcomes.json");

  if (l1 || l2 || l3 || l4) return <Loader />;
  if (e1 || e2 || e3 || e4) return <Loader error={e1 || e2 || e3 || e4} />;

  const totalPatients = demo.race.reduce((s, d) => s + d.count, 0);
  const covidCount    = conds.find((c) => c.label === "COVID-19")?.count ?? 0;
  const suspectedCount= conds.find((c) => c.label === "Suspected COVID-19")?.count ?? 0;
  const totalEnc      = enc.reduce((s, d) => s + d.count, 0);
  const mortality     = out ? ((out.died / (out.died + out.survived)) * 100).toFixed(1) : "—";

  return (
    <div className={styles.page}>
      <div className={styles.hero}>
        <h1>Massachusetts COVID-19<br />Synthetic Patient Data</h1>
        <p>
          10,000+ synthetic patients generated by Synthea™ representing Massachusetts during
          the early COVID-19 pandemic (2019–2020). Explore demographics, clinical outcomes,
          encounter patterns, and more using the navigation on the left.
        </p>
      </div>

      <div className={styles.statsGrid}>
        <StatBox label="Total Patients"   value={totalPatients.toLocaleString()}  color="var(--accent)"    />
        <StatBox label="Confirmed COVID-19" value={covidCount.toLocaleString()}   color="var(--covid)"     sub="diagnosis code" />
        <StatBox label="Suspected COVID-19" value={suspectedCount.toLocaleString()} color="var(--yellow)"  sub="diagnosis code" />
        <StatBox label="Total Encounters" value={totalEnc.toLocaleString()}       color="var(--purple)"    />
        <StatBox label="COVID Mortality"  value={`${mortality}%`}                 color="var(--covid)"     sub="of COVID patients" />
      </div>

      <div className={styles.grid}>
        <Card title="Datasets Available" subtitle="Pre-processed from 16 Synthea CSV files">
          <ul className={styles.dataList}>
            {[
              ["patients.csv",      "12,352 rows",  "Demographics, location, vitals context"],
              ["encounters.csv",    "321,528 rows", "Visit type, class, reason codes"],
              ["conditions.csv",    "114,544 rows", "ICD diagnoses per patient"],
              ["observations.csv",  "1.6M rows",    "Labs, vitals, measurements"],
              ["medications.csv",   "431,262 rows", "Prescribed drugs + costs"],
              ["procedures.csv",    "100,427 rows", "Clinical procedures performed"],
              ["payers.csv",        "10 rows",      "Insurance payer summaries"],
              ["immunizations.csv", "16,481 rows",  "Vaccine administration records"],
            ].map(([file, rows, desc]) => (
              <li key={file} className={styles.dataRow}>
                <span className={styles.filename}>{file}</span>
                <span className={styles.rows}>{rows}</span>
                <span className={styles.desc}>{desc}</span>
              </li>
            ))}
          </ul>
        </Card>

        <Card title="Visualizations" subtitle="What you can explore">
          <ul className={styles.vizList}>
            {[
              ["COVID Timeline",      "Area chart of confirmed + suspected cases by month"],
              ["Demographics",        "Race and gender donut charts"],
              ["Conditions",          "Top diagnoses + COVID comorbidities"],
              ["Encounters",          "Encounter class breakdown + COVID encounter timeline"],
              ["Age Distribution",    "Histogram comparing COVID vs. non-COVID patients"],
              ["Vitals",              "Box plots of O2 sat, temperature, BP, heart rate"],
              ["Medications",         "Top drugs prescribed to COVID patients"],
              ["Payers",              "Insurance payer coverage & quality-of-life scores"],
            ].map(([name, desc]) => (
              <li key={name} className={styles.vizRow}>
                <span className={styles.vizName}>{name}</span>
                <span className={styles.vizDesc}>{desc}</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>
    </div>
  );
}
